export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#f7f5ff] font-body">
      <div className="max-w-2xl mx-auto px-6 py-16">
        <p className="text-xs font-semibold text-primary-medium uppercase tracking-widest mb-2">Legal</p>
        <h1 className="font-display text-4xl font-semibold text-[#1a1a2e] mb-2">Terms of Use</h1>
        <p className="text-sm text-[#9090b0] mb-12">Last updated: June 2025</p>

        <div className="space-y-10 text-sm text-[#5a5a7a] leading-relaxed">

          <section>
            <h2 className="font-display text-xl font-semibold text-[#1a1a2e] mb-3">Use of service</h2>
            <p>RoundOne is a free tool for interview practice. By using it, you agree to use it for its intended purpose and not to abuse, reverse engineer, or attempt to compromise the platform.</p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-[#1a1a2e] mb-3">Your content</h2>
            <p>The answers you provide during interviews are yours. We store them to generate your results and history. You can delete all your content at any time by deleting your account from Settings.</p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-[#1a1a2e] mb-3">AI-generated content</h2>
            <p>Questions and feedback are generated by Google's Gemini AI. While we prompt it carefully, AI can make mistakes. Do not treat RoundOne feedback as a substitute for real interview preparation or professional career advice.</p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-[#1a1a2e] mb-3">Availability</h2>
            <p>RoundOne is provided as-is, free of charge. We make no guarantees about uptime or availability. The service may change or be discontinued at any time.</p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-[#1a1a2e] mb-3">Limitation of liability</h2>
            <p>RoundOne is not responsible for any outcomes related to your use of this service, including interview results or employment decisions.</p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-[#1a1a2e] mb-3">Contact</h2>
            <p>Questions? Reach out via GitHub: <a href="https://github.com/anasalam-xyz" className="text-primary-medium hover:text-primary-dark transition-colors">github.com/anasalam-xyz</a></p>
          </section>

        </div>
      </div>
    </div>
  );
}
